spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: hutuoj-backend-user-service
          uri: lb://hutuoj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: hutuoj-backend-question-service
          uri: lb://hutuoj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: hutuoj-backend-judge-service
          uri: lb://hutuoj-backend-judge-service
          predicates:
            - Path=/api/judge/**
  application:
    name: hutuoj-backend-gateway
  main:
    web-application-type: reactive
server:
  port: 8101
knife4j:
  gateway:
    # \u2460 \u7B2C\u4E00\u4E2A\u914D\u7F6E\uFF0C\u5F00\u542Fgateway\u805A\u5408\u7EC4\u4EF6
    enabled: true
    # \u2461 \u7B2C\u4E8C\u884C\u914D\u7F6E\uFF0C\u8BBE\u7F6E\u805A\u5408\u6A21\u5F0F\u91C7\u7528discover\u670D\u52A1\u53D1\u73B0\u7684\u6A21\u5F0F
    strategy: discover
    discover:
      # \u2462 \u7B2C\u4E09\u884C\u914D\u7F6E\uFF0C\u5F00\u542Fdiscover\u6A21\u5F0F
      enabled: true
      # \u2463 \u7B2C\u56DB\u884C\u914D\u7F6E\uFF0C\u805A\u5408\u5B50\u670D\u52A1\u5168\u90E8\u4E3ASwagger2\u89C4\u8303\u7684\u6587\u6863
      version: swagger2
